version: "3.9"
services:
  ui:
    build:
      context: ./route-visualizer-ui
    ports:
      - "5050:3000"
  api:
    build:
      context: ./route-visualizer-api
    ports:
      - "5001:5001"
      - "4000:4000"